# Consume metadata for libsndfile 1.0.31 (depends on ogg/vorbis/flac/opus).
# Entrypoints: _Populate (prebuilt), _PopulateBuild (from source), _PopulateSystem.

set(libsndfile_release_base "https://github.com/kryksyh/muse_deps_private/releases/download/libsndfile-1.0.31")
set(libsndfile_recipe_base  "https://raw.githubusercontent.com/kryksyh/muse_deps_private/main")

function(_libsndfile_set_from_prefix prefix os)
    set(inc ${prefix}/include)
    if (os STREQUAL "linux")
        set(libs ${prefix}/lib/libsndfile.so.1.0.31 ${prefix}/lib/libsndfile.so.1 ${prefix}/lib/libsndfile.so)
        set(install ${libs})
    elseif (os STREQUAL "macos")
        set(libs ${prefix}/lib/libsndfile.1.0.31.dylib ${prefix}/lib/libsndfile.1.dylib ${prefix}/lib/libsndfile.dylib)
        set(install ${libs})
    elseif (os STREQUAL "windows")
        set(libs ${prefix}/lib/sndfile.lib)
        set(install ${prefix}/bin/sndfile.dll)
    else()
        message(FATAL_ERROR "[libsndfile] Not supported os: ${os}")
    endif()

    if(NOT TARGET SndFile::sndfile)
       add_library(SndFile::sndfile INTERFACE IMPORTED GLOBAL)
       target_include_directories(SndFile::sndfile INTERFACE ${inc})
       target_link_libraries(SndFile::sndfile INTERFACE ${libs})
    endif()
    set_property(GLOBAL PROPERTY libsndfile_INCLUDE_DIRS ${inc})
    set_property(GLOBAL PROPERTY libsndfile_LIBRARIES ${libs})
    set_property(GLOBAL PROPERTY libsndfile_INSTALL_LIBRARIES ${install})
endfunction()

function(libsndfile_Populate remote_url local_path os arch build_type)
    if (os STREQUAL "linux")
        set(name "linux_${arch}_relwithdebinfo_gcc10")
    elseif (os STREQUAL "macos")
        if (arch STREQUAL "x86_64")
            set(name "macos_x86_64_relwithdebinfo_appleclang15_os109")
        elseif (arch STREQUAL "aarch64")
            set(name "macos_aarch64_relwithdebinfo_appleclang15_os1013")
        elseif (arch STREQUAL "universal")
            set(name "macos_universal_relwithdebinfo_appleclang15_os1013")
        else()
            set_property(GLOBAL PROPERTY libsndfile_AVAILABLE FALSE)
            return()
        endif()
    elseif (os STREQUAL "windows")
        set(bt ${build_type})
        if (bt STREQUAL "release")
            set(bt "relwithdebinfo")
        endif()
        set(name "windows_${arch}_${bt}_msvc192")
    else()
        set_property(GLOBAL PROPERTY libsndfile_AVAILABLE FALSE)
        return()
    endif()

    if (NOT EXISTS ${local_path}/${name}.7z)
        file(MAKE_DIRECTORY ${local_path})
        message(STATUS "[libsndfile] prebuilt: ${libsndfile_release_base}/${name}.7z")
        file(DOWNLOAD ${libsndfile_release_base}/${name}.7z ${local_path}/${name}.7z)
    endif()

    set(valid FALSE)
    if (EXISTS ${local_path}/${name}.7z)
        file(READ ${local_path}/${name}.7z magic LIMIT 6 HEX)
        if (magic STREQUAL "377abcaf271c")
            set(valid TRUE)
        endif()
    endif()
    if (NOT valid)
        file(REMOVE ${local_path}/${name}.7z)
        set_property(GLOBAL PROPERTY libsndfile_AVAILABLE FALSE)
        return()
    endif()

    if (NOT EXISTS ${local_path}/include)
        file(ARCHIVE_EXTRACT INPUT ${local_path}/${name}.7z DESTINATION ${local_path})
    endif()

    _libsndfile_set_from_prefix(${local_path} ${os})
    set_property(GLOBAL PROPERTY libsndfile_AVAILABLE TRUE)
endfunction()

function(libsndfile_PopulateBuild remote_url local_path os arch build_type)
    set(recipe_dir "${local_path}/recipe")
    file(MAKE_DIRECTORY "${recipe_dir}/patch")
    if (NOT EXISTS "${local_path}/build_dep_lib.cmake")
        file(DOWNLOAD ${libsndfile_recipe_base}/buildtools/build_dep_lib.cmake ${local_path}/build_dep_lib.cmake)
    endif()
    if (NOT EXISTS "${recipe_dir}/spec.cmake")
        file(DOWNLOAD ${libsndfile_recipe_base}/libsndfile/1.0.31/recipe/spec.cmake ${recipe_dir}/spec.cmake)
    endif()
    include("${recipe_dir}/spec.cmake")
    foreach(pf ${DEP_PATCHES})
        if (NOT EXISTS "${recipe_dir}/${pf}")
            file(DOWNLOAD ${libsndfile_recipe_base}/libsndfile/1.0.31/recipe/${pf} ${recipe_dir}/${pf})
        endif()
    endforeach()

    set(dep_prefixes "")
    foreach(dv ${DEP_DEPENDS})
        string(REPLACE "/" ";" _p "${dv}")
        list(GET _p 0 _dn)
        list(APPEND dep_prefixes "${local_path}/../${_dn}")
    endforeach()

    message(STATUS "[libsndfile] building from source -> ${local_path}")
    include("${local_path}/build_dep_lib.cmake")
    build_dep(NAME libsndfile RECIPE_DIR "${recipe_dir}" OS ${os} ARCH ${arch}
              BUILDTYPE ${build_type} WORK "${local_path}/work" INSTALL_DIR "${local_path}"
              DEPENDS_PREFIXES "${dep_prefixes}")

    _libsndfile_set_from_prefix(${local_path} ${os})
endfunction()

function(libsndfile_PopulateSystem)
    find_path(libsndfile_INCLUDE_DIR NAMES sndfile.h)
    find_library(libsndfile_LIBRARY NAMES sndfile)
    if (NOT libsndfile_INCLUDE_DIR OR NOT libsndfile_LIBRARY)
        message(FATAL_ERROR "[libsndfile] system libsndfile not found (USE_SYSTEM enabled)")
    endif()
    if(NOT TARGET SndFile::sndfile)
       add_library(SndFile::sndfile INTERFACE IMPORTED GLOBAL)
       target_include_directories(SndFile::sndfile INTERFACE ${libsndfile_INCLUDE_DIR})
       target_link_libraries(SndFile::sndfile INTERFACE ${libsndfile_LIBRARY})
    endif()
    set_property(GLOBAL PROPERTY libsndfile_INCLUDE_DIRS ${libsndfile_INCLUDE_DIR})
    set_property(GLOBAL PROPERTY libsndfile_LIBRARIES ${libsndfile_LIBRARY})
    set_property(GLOBAL PROPERTY libsndfile_INSTALL_LIBRARIES "")
endfunction()
