# Consume metadata for wavpack 5.7.0. Entrypoints: _Populate (prebuilt),
# _PopulateBuild (from source), _PopulateSystem (system).

set(wavpack_recipe_base  "https://raw.githubusercontent.com/kryksyh/muse_deps_private/main")

function(_wavpack_set_from_prefix prefix os)
    set(inc ${prefix}/include)
    if (os STREQUAL "linux")
        set(libs ${prefix}/lib/libwavpack.so.1.2.6 ${prefix}/lib/libwavpack.so.1 ${prefix}/lib/libwavpack.so)
        set(install ${libs})
    elseif (os STREQUAL "macos")
        set(libs ${prefix}/lib/libwavpack.1.dylib ${prefix}/lib/libwavpack.dylib)
        set(install ${libs})
    elseif (os STREQUAL "windows")
        set(libs ${prefix}/lib/wavpackdll.lib)
        set(install ${prefix}/bin/wavpackdll.dll)
    else()
        message(FATAL_ERROR "[wavpack] Not supported os: ${os}")
    endif()

    if(NOT TARGET wavpack::wavpack)
       add_library(wavpack::wavpack INTERFACE IMPORTED GLOBAL)
       target_include_directories(wavpack::wavpack INTERFACE ${inc})
       target_link_libraries(wavpack::wavpack INTERFACE ${libs})
    endif()
    set_property(GLOBAL PROPERTY wavpack_INCLUDE_DIRS ${inc})
    set_property(GLOBAL PROPERTY wavpack_LIBRARIES ${libs})
    set_property(GLOBAL PROPERTY wavpack_INSTALL_LIBRARIES ${install})
endfunction()

function(wavpack_Populate local_path os arch build_type version)
    if (os STREQUAL "linux")
        set(name "linux_${arch}_relwithdebinfo_gcc10")
    elseif (os STREQUAL "macos")
        if (arch STREQUAL "x86_64")
            set(name "macos_x86_64_relwithdebinfo_appleclang15_os109")
        elseif (arch STREQUAL "aarch64")
            set(name "macos_aarch64_relwithdebinfo_appleclang15_os1013")
        elseif (arch STREQUAL "universal")
            set(name "macos_universal_relwithdebinfo_appleclang15_os1013")
        else()
            set_property(GLOBAL PROPERTY wavpack_AVAILABLE FALSE)
            return()
        endif()
    elseif (os STREQUAL "windows")
        set(bt ${build_type})
        if (bt STREQUAL "release")
            set(bt "relwithdebinfo")
        endif()
        set(name "windows_${arch}_${bt}_msvc192")
    else()
        set_property(GLOBAL PROPERTY wavpack_AVAILABLE FALSE)
        return()
    endif()

    if (NOT EXISTS ${local_path}/${name}.7z)
        file(MAKE_DIRECTORY ${local_path})
        message(STATUS "[wavpack] prebuilt: https://github.com/kryksyh/muse_deps_private/releases/download/wavpack-${version}/${name}.7z")
        file(DOWNLOAD https://github.com/kryksyh/muse_deps_private/releases/download/wavpack-${version}/${name}.7z ${local_path}/${name}.7z)
    endif()

    set(valid FALSE)
    if (EXISTS ${local_path}/${name}.7z)
        file(READ ${local_path}/${name}.7z magic LIMIT 6 HEX)
        if (magic STREQUAL "377abcaf271c")
            set(valid TRUE)
        endif()
    endif()
    if (NOT valid)
        file(REMOVE ${local_path}/${name}.7z)
        set_property(GLOBAL PROPERTY wavpack_AVAILABLE FALSE)
        return()
    endif()

    if (NOT EXISTS ${local_path}/include)
        file(ARCHIVE_EXTRACT INPUT ${local_path}/${name}.7z DESTINATION ${local_path})
    endif()

    _wavpack_set_from_prefix(${local_path} ${os})
    set_property(GLOBAL PROPERTY wavpack_AVAILABLE TRUE)
endfunction()

function(wavpack_PopulateBuild local_path os arch build_type version)
    set(recipe_dir "${local_path}/recipe")
    file(MAKE_DIRECTORY "${recipe_dir}/patch")
    if (NOT EXISTS "${local_path}/build_dep_lib.cmake")
        file(DOWNLOAD ${wavpack_recipe_base}/buildtools/build_dep_lib.cmake ${local_path}/build_dep_lib.cmake)
    endif()
    if (NOT EXISTS "${recipe_dir}/spec.cmake")
        file(DOWNLOAD ${wavpack_recipe_base}/wavpack/${version}/recipe/spec.cmake ${recipe_dir}/spec.cmake)
    endif()
    include("${recipe_dir}/spec.cmake")
    foreach(pf ${DEP_PATCHES})
        if (NOT EXISTS "${recipe_dir}/${pf}")
            file(DOWNLOAD ${wavpack_recipe_base}/wavpack/${version}/recipe/${pf} ${recipe_dir}/${pf})
        endif()
    endforeach()

    message(STATUS "[wavpack] building from source -> ${local_path}")
    include("${local_path}/build_dep_lib.cmake")
    build_dep(NAME wavpack RECIPE_DIR "${recipe_dir}" OS ${os} ARCH ${arch}
              BUILDTYPE ${build_type} WORK "${local_path}/work" INSTALL_DIR "${local_path}")

    _wavpack_set_from_prefix(${local_path} ${os})
endfunction()

function(wavpack_PopulateSystem)
    find_path(wavpack_INCLUDE_DIR NAMES wavpack/wavpack.h)
    find_library(wavpack_LIBRARY NAMES wavpack)
    if (NOT wavpack_INCLUDE_DIR OR NOT wavpack_LIBRARY)
        message(FATAL_ERROR "[wavpack] system wavpack not found (USE_SYSTEM enabled)")
    endif()
    if(NOT TARGET wavpack::wavpack)
       add_library(wavpack::wavpack INTERFACE IMPORTED GLOBAL)
       target_include_directories(wavpack::wavpack INTERFACE ${wavpack_INCLUDE_DIR})
       target_link_libraries(wavpack::wavpack INTERFACE ${wavpack_LIBRARY})
    endif()
    set_property(GLOBAL PROPERTY wavpack_INCLUDE_DIRS ${wavpack_INCLUDE_DIR})
    set_property(GLOBAL PROPERTY wavpack_LIBRARIES ${wavpack_LIBRARY})
    set_property(GLOBAL PROPERTY wavpack_INSTALL_LIBRARIES "")
endfunction()
