# Consume metadata for zlib 1.2.13 (macOS + Windows only; AU does not use it on Linux).
# Source build is NOT yet supported: zlib 1.2.13 fails to compile on modern clang
# (K&R prototypes) and needs a patch. Use prebuilt or MUSE_USE_SYSTEM_ZLIB.

set(zlib_release_base "https://github.com/kryksyh/muse_deps_private/releases/download/zlib-1.2.13")

function(_zlib_set_from_prefix prefix os)
    set(inc ${prefix}/include)
    if (os STREQUAL "macos")
        set(libs ${prefix}/lib/libz.1.2.13.dylib)
        set(install ${prefix}/lib/libz.1.2.13.dylib ${prefix}/lib/libz.1.dylib ${prefix}/lib/libz.dylib)
    elseif (os STREQUAL "windows")
        set(libs ${prefix}/lib/zdll.lib)
        set(install ${prefix}/bin/zlib1.dll)
    else()
        message(FATAL_ERROR "[zlib] Not supported os: ${os}")
    endif()

    if(NOT TARGET zlib::zlib)
       add_library(zlib::zlib INTERFACE IMPORTED GLOBAL)
       target_include_directories(zlib::zlib INTERFACE ${inc})
       target_link_libraries(zlib::zlib INTERFACE ${libs})
    endif()
    set_property(GLOBAL PROPERTY zlib_INCLUDE_DIRS ${inc})
    set_property(GLOBAL PROPERTY zlib_LIBRARIES ${libs})
    set_property(GLOBAL PROPERTY zlib_INSTALL_LIBRARIES ${install})
endfunction()

function(zlib_Populate remote_url local_path os arch build_type)
    if (os STREQUAL "macos")
        if (arch STREQUAL "x86_64")
            set(name "zlib_macos_x86_64_relwithdebinfo_appleclang15_os109")
        elseif (arch STREQUAL "aarch64")
            set(name "zlib_macos_aarch64_relwithdebinfo_appleclang15_os1013")
        elseif (arch STREQUAL "universal")
            set(name "zlib_macos_universal_relwithdebinfo_appleclang15_os1013")
        else()
            set_property(GLOBAL PROPERTY zlib_AVAILABLE FALSE)
            return()
        endif()
    elseif (os STREQUAL "windows")
        set(bt ${build_type})
        if (bt STREQUAL "release")
            set(bt "relwithdebinfo")
        endif()
        set(name "zlib_windows_${arch}_${bt}_msvc192")
    else()
        set_property(GLOBAL PROPERTY zlib_AVAILABLE FALSE)
        return()
    endif()

    if (NOT EXISTS ${local_path}/${name}.7z)
        file(MAKE_DIRECTORY ${local_path})
        message(STATUS "[zlib] prebuilt: ${zlib_release_base}/${name}.7z")
        file(DOWNLOAD ${zlib_release_base}/${name}.7z ${local_path}/${name}.7z)
    endif()

    set(valid FALSE)
    if (EXISTS ${local_path}/${name}.7z)
        file(READ ${local_path}/${name}.7z magic LIMIT 6 HEX)
        if (magic STREQUAL "377abcaf271c")
            set(valid TRUE)
        endif()
    endif()
    if (NOT valid)
        file(REMOVE ${local_path}/${name}.7z)
        set_property(GLOBAL PROPERTY zlib_AVAILABLE FALSE)
        return()
    endif()

    if (NOT EXISTS ${local_path}/include)
        file(ARCHIVE_EXTRACT INPUT ${local_path}/${name}.7z DESTINATION ${local_path})
    endif()

    _zlib_set_from_prefix(${local_path} ${os})
    set_property(GLOBAL PROPERTY zlib_AVAILABLE TRUE)
endfunction()

function(zlib_PopulateBuild remote_url local_path os arch build_type)
    message(FATAL_ERROR "[zlib] source build not supported (zlib 1.2.13 needs a patch for modern clang). Use the prebuilt or MUSE_USE_SYSTEM_ZLIB.")
endfunction()

function(zlib_PopulateSystem)
    find_path(zlib_INCLUDE_DIR NAMES zlib.h)
    find_library(zlib_LIBRARY NAMES z)
    if (NOT zlib_INCLUDE_DIR OR NOT zlib_LIBRARY)
        message(FATAL_ERROR "[zlib] system zlib not found (USE_SYSTEM enabled)")
    endif()
    if(NOT TARGET zlib::zlib)
       add_library(zlib::zlib INTERFACE IMPORTED GLOBAL)
       target_include_directories(zlib::zlib INTERFACE ${zlib_INCLUDE_DIR})
       target_link_libraries(zlib::zlib INTERFACE ${zlib_LIBRARY})
    endif()
    set_property(GLOBAL PROPERTY zlib_INCLUDE_DIRS ${zlib_INCLUDE_DIR})
    set_property(GLOBAL PROPERTY zlib_LIBRARIES ${zlib_LIBRARY})
    set_property(GLOBAL PROPERTY zlib_INSTALL_LIBRARIES "")
endfunction()
