# Consume metadata for portaudio 19.7.0. Entrypoints: _Populate (prebuilt),
# _PopulateBuild (from source), _PopulateSystem (system).

set(portaudio_release_base "https://github.com/kryksyh/muse_deps_private/releases/download/portaudio-19.7.0")
set(portaudio_recipe_base  "https://raw.githubusercontent.com/kryksyh/muse_deps_private/main")

function(_portaudio_set_from_prefix prefix os)
    set(inc ${prefix}/include)
    if (os STREQUAL "linux")
        set(libs ${prefix}/lib/libportaudio.so)
        set(install ${libs})
    elseif (os STREQUAL "macos")
        set(libs ${prefix}/lib/libportaudio.dylib)
        set(install ${libs})
    elseif (os STREQUAL "windows")
        # windows lib names to be confirmed against CI CMake output
        set(libs ${prefix}/lib/portaudio_x64.lib)
        set(install ${prefix}/bin/portaudio_x64.dll)
    else()
        message(FATAL_ERROR "[portaudio] Not supported os: ${os}")
    endif()

    if(NOT TARGET portaudio::portaudio)
       add_library(portaudio::portaudio INTERFACE IMPORTED GLOBAL)
       target_include_directories(portaudio::portaudio INTERFACE ${inc})
       target_link_libraries(portaudio::portaudio INTERFACE ${libs})
    endif()
    set_property(GLOBAL PROPERTY portaudio_INCLUDE_DIRS ${inc})
    set_property(GLOBAL PROPERTY portaudio_LIBRARIES ${libs})
    set_property(GLOBAL PROPERTY portaudio_INSTALL_LIBRARIES ${install})
endfunction()

function(portaudio_Populate remote_url local_path os arch build_type)
    if (os STREQUAL "linux")
        set(name "linux_${arch}_relwithdebinfo_gcc10")
    elseif (os STREQUAL "macos")
        if (arch STREQUAL "x86_64")
            set(name "macos_x86_64_relwithdebinfo_appleclang15_os109")
        elseif (arch STREQUAL "aarch64")
            set(name "macos_aarch64_relwithdebinfo_appleclang15_os1013")
        elseif (arch STREQUAL "universal")
            set(name "macos_universal_relwithdebinfo_appleclang15_os1013")
        else()
            set_property(GLOBAL PROPERTY portaudio_AVAILABLE FALSE)
            return()
        endif()
    elseif (os STREQUAL "windows")
        set(bt ${build_type})
        if (bt STREQUAL "release")
            set(bt "relwithdebinfo")
        endif()
        set(name "windows_${arch}_${bt}_msvc192")
    else()
        set_property(GLOBAL PROPERTY portaudio_AVAILABLE FALSE)
        return()
    endif()

    if (NOT EXISTS ${local_path}/${name}.7z)
        file(MAKE_DIRECTORY ${local_path})
        message(STATUS "[portaudio] prebuilt: ${portaudio_release_base}/${name}.7z")
        file(DOWNLOAD ${portaudio_release_base}/${name}.7z ${local_path}/${name}.7z)
    endif()

    set(valid FALSE)
    if (EXISTS ${local_path}/${name}.7z)
        file(READ ${local_path}/${name}.7z magic LIMIT 6 HEX)
        if (magic STREQUAL "377abcaf271c")
            set(valid TRUE)
        endif()
    endif()
    if (NOT valid)
        file(REMOVE ${local_path}/${name}.7z)
        set_property(GLOBAL PROPERTY portaudio_AVAILABLE FALSE)
        return()
    endif()

    if (NOT EXISTS ${local_path}/include)
        file(ARCHIVE_EXTRACT INPUT ${local_path}/${name}.7z DESTINATION ${local_path})
    endif()

    _portaudio_set_from_prefix(${local_path} ${os})
    set_property(GLOBAL PROPERTY portaudio_AVAILABLE TRUE)
endfunction()

function(portaudio_PopulateBuild remote_url local_path os arch build_type)
    set(recipe_dir "${local_path}/recipe")
    file(MAKE_DIRECTORY "${recipe_dir}/patch")
    if (NOT EXISTS "${local_path}/build_dep_lib.cmake")
        file(DOWNLOAD ${portaudio_recipe_base}/buildtools/build_dep_lib.cmake ${local_path}/build_dep_lib.cmake)
    endif()
    if (NOT EXISTS "${recipe_dir}/spec.cmake")
        file(DOWNLOAD ${portaudio_recipe_base}/portaudio/19.7.0/recipe/spec.cmake ${recipe_dir}/spec.cmake)
    endif()
    include("${recipe_dir}/spec.cmake")
    foreach(pf ${DEP_PATCHES})
        if (NOT EXISTS "${recipe_dir}/${pf}")
            file(DOWNLOAD ${portaudio_recipe_base}/portaudio/19.7.0/recipe/${pf} ${recipe_dir}/${pf})
        endif()
    endforeach()

    message(STATUS "[portaudio] building from source -> ${local_path}")
    include("${local_path}/build_dep_lib.cmake")
    build_dep(NAME portaudio RECIPE_DIR "${recipe_dir}" OS ${os} ARCH ${arch}
              BUILDTYPE ${build_type} WORK "${local_path}/work" INSTALL_DIR "${local_path}")

    _portaudio_set_from_prefix(${local_path} ${os})
endfunction()

function(portaudio_PopulateSystem)
    find_path(portaudio_INCLUDE_DIR NAMES portaudio.h)
    find_library(portaudio_LIBRARY NAMES portaudio)
    if (NOT portaudio_INCLUDE_DIR OR NOT portaudio_LIBRARY)
        message(FATAL_ERROR "[portaudio] system portaudio not found (USE_SYSTEM enabled)")
    endif()
    if(NOT TARGET portaudio::portaudio)
       add_library(portaudio::portaudio INTERFACE IMPORTED GLOBAL)
       target_include_directories(portaudio::portaudio INTERFACE ${portaudio_INCLUDE_DIR})
       target_link_libraries(portaudio::portaudio INTERFACE ${portaudio_LIBRARY})
    endif()
    set_property(GLOBAL PROPERTY portaudio_INCLUDE_DIRS ${portaudio_INCLUDE_DIR})
    set_property(GLOBAL PROPERTY portaudio_LIBRARIES ${portaudio_LIBRARY})
    set_property(GLOBAL PROPERTY portaudio_INSTALL_LIBRARIES "")
endfunction()
