# Pinned version — single source of truth for this dep (the consumer reads it;
# the muse_deps ref pins the whole set atomically).
set(DEP_VERSION 1.4.2)

# Consume metadata for flac. Two distinct targets (FLAC, FLAC++) -> override.
function(flac_consume_override mode local_path os arch buildtype version)
    if(mode STREQUAL "system")
        find_path(flac_INCLUDE_DIR NAMES FLAC/all.h)
        find_library(flac_LIBRARY NAMES FLAC)
        find_library(flacpp_LIBRARY NAMES FLAC++)
        if(NOT flac_INCLUDE_DIR OR NOT flac_LIBRARY OR NOT flacpp_LIBRARY)
            message(FATAL_ERROR "[flac] system FLAC/FLAC++ not found (USE_SYSTEM)")
        endif()
        set(inc "${flac_INCLUDE_DIR}")
        set(libs "${flac_LIBRARY}")
        set(libspp "${flacpp_LIBRARY}")
        set(install "")
    else()
        # prebuilt (unless forced rebuild), else build — both populate local_path
        # the same way, so resolution from the prefix is identical.
        set(_ok FALSE)
        if(NOT mode STREQUAL "rebuild")
            _muse_fetch_prebuilt(flac "${local_path}" "${os}" "${arch}" "${version}" _ok)
        endif()
        if(NOT _ok)
            _muse_build(flac "${local_path}" "${os}" "${arch}" "${buildtype}")
        endif()
        set(inc "${local_path}/include")
        _muse_resolve_libs("${local_path}" "${os}" "FLAC" libs fb)
        _muse_resolve_libs("${local_path}" "${os}" "FLAC++" libspp fppb)
        set(install ${fb} ${fppb})
    endif()
    if(NOT TARGET FLAC::FLAC)
        add_library(FLAC::FLAC INTERFACE IMPORTED GLOBAL)
        target_include_directories(FLAC::FLAC INTERFACE ${inc})
        target_link_libraries(FLAC::FLAC INTERFACE ${libs})
    endif()
    if(NOT TARGET FLAC::FLAC++)
        add_library(FLAC::FLAC++ INTERFACE IMPORTED GLOBAL)
        target_include_directories(FLAC::FLAC++ INTERFACE ${inc})
        target_link_libraries(FLAC::FLAC++ INTERFACE ${libspp})
    endif()
    set_property(GLOBAL PROPERTY flac_INCLUDE_DIRS ${inc})
    set_property(GLOBAL PROPERTY flac_LIBRARIES ${libs})
    set_property(GLOBAL PROPERTY flacpp_LIBRARIES ${libspp})
    set_property(GLOBAL PROPERTY flac_INSTALL_LIBRARIES ${install})
endfunction()
