# Consume metadata for flac 1.4.2 (depends on ogg). Provides FLAC::FLAC and
# FLAC::FLAC++. Entrypoints: _Populate (prebuilt), _PopulateBuild, _PopulateSystem.

set(flac_recipe_base  "https://raw.githubusercontent.com/kryksyh/muse_deps_private/main")

function(_flac_set_from_prefix prefix os)
    set(inc ${prefix}/include)
    if (os STREQUAL "linux")
        set(libs ${prefix}/lib/libFLAC.so.12.0.0 ${prefix}/lib/libFLAC.so.12 ${prefix}/lib/libFLAC.so)
        set(libspp ${prefix}/lib/libFLAC++.so.10.0.0 ${prefix}/lib/libFLAC++.so.10 ${prefix}/lib/libFLAC++.so)
    elseif (os STREQUAL "macos")
        set(libs ${prefix}/lib/libFLAC.12.0.0.dylib ${prefix}/lib/libFLAC.12.dylib ${prefix}/lib/libFLAC.dylib)
        set(libspp ${prefix}/lib/libFLAC++.10.0.0.dylib ${prefix}/lib/libFLAC++.10.dylib ${prefix}/lib/libFLAC++.dylib)
    elseif (os STREQUAL "windows")
        # link the import libs; bundle the runtime DLLs
        set(libs ${prefix}/lib/FLAC.lib)
        set(libspp ${prefix}/lib/FLAC++.lib)
        set(install ${prefix}/bin/FLAC.dll ${prefix}/bin/FLAC++.dll)
    else()
        message(FATAL_ERROR "[flac] Not supported os: ${os}")
    endif()
    if(NOT DEFINED install)
        set(install ${libs} ${libspp})
    endif()

    if(NOT TARGET FLAC::FLAC)
       add_library(FLAC::FLAC INTERFACE IMPORTED GLOBAL)
       target_include_directories(FLAC::FLAC INTERFACE ${inc})
       target_link_libraries(FLAC::FLAC INTERFACE ${libs})
    endif()
    if(NOT TARGET FLAC::FLAC++)
       add_library(FLAC::FLAC++ INTERFACE IMPORTED GLOBAL)
       target_include_directories(FLAC::FLAC++ INTERFACE ${inc})
       target_link_libraries(FLAC::FLAC++ INTERFACE ${libspp})
    endif()
    set_property(GLOBAL PROPERTY flac_INCLUDE_DIRS ${inc})
    set_property(GLOBAL PROPERTY flac_LIBRARIES ${libs})
    set_property(GLOBAL PROPERTY flacpp_LIBRARIES ${libspp})
    set_property(GLOBAL PROPERTY flac_INSTALL_LIBRARIES ${install})
endfunction()

function(flac_Populate local_path os arch build_type version)
    if (os STREQUAL "linux")
        set(name "linux_${arch}_relwithdebinfo_gcc10")
    elseif (os STREQUAL "macos")
        if (arch STREQUAL "x86_64")
            set(name "macos_x86_64_relwithdebinfo_appleclang15_os109")
        elseif (arch STREQUAL "aarch64")
            set(name "macos_aarch64_relwithdebinfo_appleclang15_os1013")
        elseif (arch STREQUAL "universal")
            set(name "macos_universal_relwithdebinfo_appleclang15_os1013")
        else()
            set_property(GLOBAL PROPERTY flac_AVAILABLE FALSE)
            return()
        endif()
    elseif (os STREQUAL "windows")
        set(bt ${build_type})
        if (bt STREQUAL "release")
            set(bt "relwithdebinfo")
        endif()
        set(name "windows_${arch}_${bt}_msvc192")
    else()
        set_property(GLOBAL PROPERTY flac_AVAILABLE FALSE)
        return()
    endif()

    if (NOT EXISTS ${local_path}/${name}.7z)
        file(MAKE_DIRECTORY ${local_path})
        message(STATUS "[flac] prebuilt: https://github.com/kryksyh/muse_deps_private/releases/download/flac-${version}/${name}.7z")
        file(DOWNLOAD https://github.com/kryksyh/muse_deps_private/releases/download/flac-${version}/${name}.7z ${local_path}/${name}.7z)
    endif()

    set(valid FALSE)
    if (EXISTS ${local_path}/${name}.7z)
        file(READ ${local_path}/${name}.7z magic LIMIT 6 HEX)
        if (magic STREQUAL "377abcaf271c")
            set(valid TRUE)
        endif()
    endif()
    if (NOT valid)
        file(REMOVE ${local_path}/${name}.7z)
        set_property(GLOBAL PROPERTY flac_AVAILABLE FALSE)
        return()
    endif()

    if (NOT EXISTS ${local_path}/include)
        file(ARCHIVE_EXTRACT INPUT ${local_path}/${name}.7z DESTINATION ${local_path})
    endif()

    _flac_set_from_prefix(${local_path} ${os})
    set_property(GLOBAL PROPERTY flac_AVAILABLE TRUE)
endfunction()

function(flac_PopulateBuild local_path os arch build_type version)
    set(recipe_dir "${local_path}/recipe")
    file(MAKE_DIRECTORY "${recipe_dir}/patch")
    if (NOT EXISTS "${local_path}/build_dep_lib.cmake")
        file(DOWNLOAD ${flac_recipe_base}/buildtools/build_dep_lib.cmake ${local_path}/build_dep_lib.cmake)
    endif()
    if (NOT EXISTS "${recipe_dir}/spec.cmake")
        file(DOWNLOAD ${flac_recipe_base}/flac/${version}/recipe/spec.cmake ${recipe_dir}/spec.cmake)
    endif()
    include("${recipe_dir}/spec.cmake")
    foreach(pf ${DEP_PATCHES})
        if (NOT EXISTS "${recipe_dir}/${pf}")
            file(DOWNLOAD ${flac_recipe_base}/flac/${version}/recipe/${pf} ${recipe_dir}/${pf})
        endif()
    endforeach()

    set(dep_prefixes "")
    foreach(dv ${DEP_DEPENDS})
        string(REPLACE "/" ";" _p "${dv}")
        list(GET _p 0 _dn)
        list(APPEND dep_prefixes "${local_path}/../${_dn}")
    endforeach()

    message(STATUS "[flac] building from source -> ${local_path}")
    include("${local_path}/build_dep_lib.cmake")
    build_dep(NAME flac RECIPE_DIR "${recipe_dir}" OS ${os} ARCH ${arch}
              BUILDTYPE ${build_type} WORK "${local_path}/work" INSTALL_DIR "${local_path}"
              DEPENDS_PREFIXES "${dep_prefixes}")

    _flac_set_from_prefix(${local_path} ${os})
endfunction()

function(flac_PopulateSystem)
    find_path(flac_INCLUDE_DIR NAMES FLAC/all.h)
    find_library(flac_LIBRARY NAMES FLAC)
    find_library(flacpp_LIBRARY NAMES FLAC++)
    if (NOT flac_INCLUDE_DIR OR NOT flac_LIBRARY)
        message(FATAL_ERROR "[flac] system flac not found (USE_SYSTEM enabled)")
    endif()
    if(NOT TARGET FLAC::FLAC)
       add_library(FLAC::FLAC INTERFACE IMPORTED GLOBAL)
       target_include_directories(FLAC::FLAC INTERFACE ${flac_INCLUDE_DIR})
       target_link_libraries(FLAC::FLAC INTERFACE ${flac_LIBRARY})
    endif()
    if(NOT TARGET FLAC::FLAC++)
       add_library(FLAC::FLAC++ INTERFACE IMPORTED GLOBAL)
       target_include_directories(FLAC::FLAC++ INTERFACE ${flac_INCLUDE_DIR})
       target_link_libraries(FLAC::FLAC++ INTERFACE ${flacpp_LIBRARY})
    endif()
    set_property(GLOBAL PROPERTY flac_INCLUDE_DIRS ${flac_INCLUDE_DIR})
    set_property(GLOBAL PROPERTY flac_LIBRARIES ${flac_LIBRARY})
    set_property(GLOBAL PROPERTY flacpp_LIBRARIES ${flacpp_LIBRARY})
    set_property(GLOBAL PROPERTY flac_INSTALL_LIBRARIES "")
endfunction()
