# Consume metadata for expat. Entrypoints: _Populate (prebuilt), _PopulateBuild
# (from source — TODO), _PopulateSystem (system).
# NOTE: the "2.0.5" path label is historical; the actual library is expat 2.5.x.

set(expat_release_base "https://github.com/kryksyh/muse_deps_private/releases/download/expat-2.0.5")

function(_expat_set_from_prefix prefix os)
    set(inc ${prefix}/include)
    if (os STREQUAL "linux")
        set(libs ${prefix}/lib/libexpat.so.1.8.10)
        set(install ${libs})
    elseif (os STREQUAL "macos")
        set(libs ${prefix}/lib/libexpat.1.8.10.dylib)
        set(install ${libs})
    elseif (os STREQUAL "windows")
        set(libs ${prefix}/lib/libexpat.lib)
        set(install ${prefix}/bin/libexpat.dll)
    else()
        message(FATAL_ERROR "[expat] Not supported os: ${os}")
    endif()

    if(NOT TARGET expat::expat)
       add_library(expat::expat INTERFACE IMPORTED GLOBAL)
       target_include_directories(expat::expat INTERFACE ${inc})
       target_link_libraries(expat::expat INTERFACE ${libs})
    endif()
    set_property(GLOBAL PROPERTY expat_INCLUDE_DIRS ${inc})
    set_property(GLOBAL PROPERTY expat_LIBRARIES ${libs})
    set_property(GLOBAL PROPERTY expat_INSTALL_LIBRARIES ${install})
endfunction()

function(expat_Populate remote_url local_path os arch build_type)
    if (os STREQUAL "linux")
        set(name "linux_${arch}_relwithdebinfo_gcc10")
    elseif (os STREQUAL "macos")
        if (arch STREQUAL "x86_64")
            set(name "macos_x86_64_relwithdebinfo_appleclang15_os109")
        elseif (arch STREQUAL "aarch64")
            set(name "macos_aarch64_relwithdebinfo_appleclang15_os1013")
        elseif (arch STREQUAL "universal")
            set(name "macos_universal_relwithdebinfo_appleclang15_os1013")
        else()
            set_property(GLOBAL PROPERTY expat_AVAILABLE FALSE)
            return()
        endif()
    elseif (os STREQUAL "windows")
        set(bt ${build_type})
        if (bt STREQUAL "release")
            set(bt "relwithdebinfo")
        endif()
        set(name "windows_${arch}_${bt}_msvc192")
    else()
        set_property(GLOBAL PROPERTY expat_AVAILABLE FALSE)
        return()
    endif()

    if (NOT EXISTS ${local_path}/${name}.7z)
        file(MAKE_DIRECTORY ${local_path})
        message(STATUS "[expat] prebuilt: ${expat_release_base}/${name}.7z")
        file(DOWNLOAD ${expat_release_base}/${name}.7z ${local_path}/${name}.7z)
    endif()

    set(valid FALSE)
    if (EXISTS ${local_path}/${name}.7z)
        file(READ ${local_path}/${name}.7z magic LIMIT 6 HEX)
        if (magic STREQUAL "377abcaf271c")
            set(valid TRUE)
        endif()
    endif()
    if (NOT valid)
        file(REMOVE ${local_path}/${name}.7z)
        set_property(GLOBAL PROPERTY expat_AVAILABLE FALSE)
        return()
    endif()

    if (NOT EXISTS ${local_path}/include)
        file(ARCHIVE_EXTRACT INPUT ${local_path}/${name}.7z DESTINATION ${local_path})
    endif()

    _expat_set_from_prefix(${local_path} ${os})
    set_property(GLOBAL PROPERTY expat_AVAILABLE TRUE)
endfunction()

function(expat_PopulateBuild remote_url local_path os arch build_type)
    message(FATAL_ERROR "[expat] source build not yet implemented. Use prebuilt or MUSE_USE_SYSTEM_EXPAT.")
endfunction()

function(expat_PopulateSystem)
    find_path(expat_INCLUDE_DIR NAMES expat.h)
    find_library(expat_LIBRARY NAMES expat)
    if (NOT expat_INCLUDE_DIR OR NOT expat_LIBRARY)
        message(FATAL_ERROR "[expat] system expat not found (USE_SYSTEM enabled)")
    endif()
    if(NOT TARGET expat::expat)
       add_library(expat::expat INTERFACE IMPORTED GLOBAL)
       target_include_directories(expat::expat INTERFACE ${expat_INCLUDE_DIR})
       target_link_libraries(expat::expat INTERFACE ${expat_LIBRARY})
    endif()
    set_property(GLOBAL PROPERTY expat_INCLUDE_DIRS ${expat_INCLUDE_DIR})
    set_property(GLOBAL PROPERTY expat_LIBRARIES ${expat_LIBRARY})
    set_property(GLOBAL PROPERTY expat_INSTALL_LIBRARIES "")
endfunction()
