# Consume metadata for vorbis 1.3.7 (depends on ogg). Entrypoints: _Populate
# (prebuilt), _PopulateBuild (from source), _PopulateSystem (system).

set(vorbis_recipe_base  "https://raw.githubusercontent.com/kryksyh/muse_deps_private/main")

function(_vorbis_set_from_prefix prefix os)
    set(inc ${prefix}/include)
    if (os STREQUAL "linux")
        # Include the SONAME symlinks (.so.N) — dependents (libsndfile) record
        # those as NEEDED. build_dep creates them post-install (the CMake build
        # sets the soname but installs only the full-version file + bare .so).
        set(libs ${prefix}/lib/libvorbis.so.0.4.9 ${prefix}/lib/libvorbis.so.0 ${prefix}/lib/libvorbis.so
                 ${prefix}/lib/libvorbisenc.so.2.0.12 ${prefix}/lib/libvorbisenc.so.2 ${prefix}/lib/libvorbisenc.so
                 ${prefix}/lib/libvorbisfile.so.3.3.8 ${prefix}/lib/libvorbisfile.so.3 ${prefix}/lib/libvorbisfile.so)
        set(install ${libs})
    elseif (os STREQUAL "macos")
        set(libs ${prefix}/lib/libvorbis.0.4.9.dylib ${prefix}/lib/libvorbis.dylib
                 ${prefix}/lib/libvorbisenc.2.0.12.dylib ${prefix}/lib/libvorbisenc.dylib
                 ${prefix}/lib/libvorbisfile.3.3.8.dylib ${prefix}/lib/libvorbisfile.dylib)
        set(install ${libs})
    elseif (os STREQUAL "windows")
        set(libs ${prefix}/lib/vorbis.lib ${prefix}/lib/vorbisenc.lib ${prefix}/lib/vorbisfile.lib)
        set(install ${prefix}/bin/vorbis.dll ${prefix}/bin/vorbisenc.dll ${prefix}/bin/vorbisfile.dll)
    else()
        message(FATAL_ERROR "[vorbis] Not supported os: ${os}")
    endif()

    if(NOT TARGET Vorbis::vorbis)
       add_library(Vorbis::vorbis INTERFACE IMPORTED GLOBAL)
       target_include_directories(Vorbis::vorbis INTERFACE ${inc})
       target_link_libraries(Vorbis::vorbis INTERFACE ${libs})
    endif()
    set_property(GLOBAL PROPERTY vorbis_INCLUDE_DIRS ${inc})
    set_property(GLOBAL PROPERTY vorbis_LIBRARIES ${libs})
    set_property(GLOBAL PROPERTY vorbis_INSTALL_LIBRARIES ${install})
endfunction()

function(vorbis_Populate local_path os arch build_type version)
    if (os STREQUAL "linux")
        set(name "linux_${arch}_relwithdebinfo_gcc10")
    elseif (os STREQUAL "macos")
        if (arch STREQUAL "x86_64")
            set(name "macos_x86_64_relwithdebinfo_appleclang15_os109")
        elseif (arch STREQUAL "aarch64")
            set(name "macos_aarch64_relwithdebinfo_appleclang15_os1013")
        elseif (arch STREQUAL "universal")
            set(name "macos_universal_relwithdebinfo_appleclang15_os1013")
        else()
            set_property(GLOBAL PROPERTY vorbis_AVAILABLE FALSE)
            return()
        endif()
    elseif (os STREQUAL "windows")
        set(bt ${build_type})
        if (bt STREQUAL "release")
            set(bt "relwithdebinfo")
        endif()
        set(name "windows_${arch}_${bt}_msvc192")
    else()
        set_property(GLOBAL PROPERTY vorbis_AVAILABLE FALSE)
        return()
    endif()

    if (NOT EXISTS ${local_path}/${name}.7z)
        file(MAKE_DIRECTORY ${local_path})
        message(STATUS "[vorbis] prebuilt: https://github.com/kryksyh/muse_deps_private/releases/download/vorbis-${version}/${name}.7z")
        file(DOWNLOAD https://github.com/kryksyh/muse_deps_private/releases/download/vorbis-${version}/${name}.7z ${local_path}/${name}.7z)
    endif()

    set(valid FALSE)
    if (EXISTS ${local_path}/${name}.7z)
        file(READ ${local_path}/${name}.7z magic LIMIT 6 HEX)
        if (magic STREQUAL "377abcaf271c")
            set(valid TRUE)
        endif()
    endif()
    if (NOT valid)
        file(REMOVE ${local_path}/${name}.7z)
        set_property(GLOBAL PROPERTY vorbis_AVAILABLE FALSE)
        return()
    endif()

    if (NOT EXISTS ${local_path}/include)
        file(ARCHIVE_EXTRACT INPUT ${local_path}/${name}.7z DESTINATION ${local_path})
    endif()

    _vorbis_set_from_prefix(${local_path} ${os})
    set_property(GLOBAL PROPERTY vorbis_AVAILABLE TRUE)
endfunction()

function(vorbis_PopulateBuild local_path os arch build_type version)
    set(recipe_dir "${local_path}/recipe")
    file(MAKE_DIRECTORY "${recipe_dir}/patch")
    if (NOT EXISTS "${local_path}/build_dep_lib.cmake")
        file(DOWNLOAD ${vorbis_recipe_base}/buildtools/build_dep_lib.cmake ${local_path}/build_dep_lib.cmake)
    endif()
    if (NOT EXISTS "${recipe_dir}/spec.cmake")
        file(DOWNLOAD ${vorbis_recipe_base}/vorbis/${version}/recipe/spec.cmake ${recipe_dir}/spec.cmake)
    endif()
    include("${recipe_dir}/spec.cmake")
    foreach(pf ${DEP_PATCHES})
        if (NOT EXISTS "${recipe_dir}/${pf}")
            file(DOWNLOAD ${vorbis_recipe_base}/vorbis/${version}/recipe/${pf} ${recipe_dir}/${pf})
        endif()
    endforeach()

    # Dependencies are sibling prefixes already populated under _deps/<name>.
    set(dep_prefixes "")
    foreach(dv ${DEP_DEPENDS})
        string(REPLACE "/" ";" _p "${dv}")
        list(GET _p 0 _dn)
        list(APPEND dep_prefixes "${local_path}/../${_dn}")
    endforeach()

    message(STATUS "[vorbis] building from source -> ${local_path}")
    include("${local_path}/build_dep_lib.cmake")
    build_dep(NAME vorbis RECIPE_DIR "${recipe_dir}" OS ${os} ARCH ${arch}
              BUILDTYPE ${build_type} WORK "${local_path}/work" INSTALL_DIR "${local_path}"
              DEPENDS_PREFIXES "${dep_prefixes}")

    _vorbis_set_from_prefix(${local_path} ${os})
endfunction()

function(vorbis_PopulateSystem)
    find_path(vorbis_INCLUDE_DIR NAMES vorbis/codec.h)
    find_library(vorbis_LIBRARY NAMES vorbis)
    find_library(vorbisenc_LIBRARY NAMES vorbisenc)
    find_library(vorbisfile_LIBRARY NAMES vorbisfile)
    if (NOT vorbis_INCLUDE_DIR OR NOT vorbis_LIBRARY)
        message(FATAL_ERROR "[vorbis] system vorbis not found (USE_SYSTEM enabled)")
    endif()
    set(libs ${vorbis_LIBRARY} ${vorbisenc_LIBRARY} ${vorbisfile_LIBRARY})
    if(NOT TARGET Vorbis::vorbis)
       add_library(Vorbis::vorbis INTERFACE IMPORTED GLOBAL)
       target_include_directories(Vorbis::vorbis INTERFACE ${vorbis_INCLUDE_DIR})
       target_link_libraries(Vorbis::vorbis INTERFACE ${libs})
    endif()
    set_property(GLOBAL PROPERTY vorbis_INCLUDE_DIRS ${vorbis_INCLUDE_DIR})
    set_property(GLOBAL PROPERTY vorbis_LIBRARIES ${libs})
    set_property(GLOBAL PROPERTY vorbis_INSTALL_LIBRARIES "")
endfunction()
