# Consume metadata for zlib 1.2.13 (macOS + Windows only; AU does not use it on Linux).
# Source build is NOT yet supported: zlib 1.2.13 fails to compile on modern clang
# (K&R prototypes) and needs a patch. Use prebuilt or MUSE_USE_SYSTEM_ZLIB.


function(_zlib_set_from_prefix prefix os)
    set(inc ${prefix}/include)
    if (os STREQUAL "macos")
        set(libs ${prefix}/lib/libz.1.2.13.dylib)
        set(install ${prefix}/lib/libz.1.2.13.dylib ${prefix}/lib/libz.1.dylib ${prefix}/lib/libz.dylib)
    elseif (os STREQUAL "windows")
        set(libs ${prefix}/lib/zdll.lib)
        set(install ${prefix}/bin/zlib1.dll)
    else()
        message(FATAL_ERROR "[zlib] Not supported os: ${os}")
    endif()

    if(NOT TARGET zlib::zlib)
       add_library(zlib::zlib INTERFACE IMPORTED GLOBAL)
       target_include_directories(zlib::zlib INTERFACE ${inc})
       target_link_libraries(zlib::zlib INTERFACE ${libs})
    endif()
    set_property(GLOBAL PROPERTY zlib_INCLUDE_DIRS ${inc})
    set_property(GLOBAL PROPERTY zlib_LIBRARIES ${libs})
    set_property(GLOBAL PROPERTY zlib_INSTALL_LIBRARIES ${install})
endfunction()

function(zlib_Populate local_path os arch build_type version)
    if (os STREQUAL "macos")
        if (arch STREQUAL "x86_64")
            set(name "zlib_macos_x86_64_relwithdebinfo_appleclang15_os109")
        elseif (arch STREQUAL "aarch64")
            set(name "zlib_macos_aarch64_relwithdebinfo_appleclang15_os1013")
        elseif (arch STREQUAL "universal")
            set(name "zlib_macos_universal_relwithdebinfo_appleclang15_os1013")
        else()
            set_property(GLOBAL PROPERTY zlib_AVAILABLE FALSE)
            return()
        endif()
    elseif (os STREQUAL "windows")
        set(bt ${build_type})
        if (bt STREQUAL "release")
            set(bt "relwithdebinfo")
        endif()
        set(name "zlib_windows_${arch}_${bt}_msvc192")
    else()
        set_property(GLOBAL PROPERTY zlib_AVAILABLE FALSE)
        return()
    endif()

    if (NOT EXISTS ${local_path}/${name}.7z)
        file(MAKE_DIRECTORY ${local_path})
        message(STATUS "[zlib] prebuilt: https://github.com/kryksyh/muse_deps_private/releases/download/zlib-${version}/${name}.7z")
        file(DOWNLOAD https://github.com/kryksyh/muse_deps_private/releases/download/zlib-${version}/${name}.7z ${local_path}/${name}.7z)
    endif()

    set(valid FALSE)
    if (EXISTS ${local_path}/${name}.7z)
        file(READ ${local_path}/${name}.7z magic LIMIT 6 HEX)
        if (magic STREQUAL "377abcaf271c")
            set(valid TRUE)
        endif()
    endif()
    if (NOT valid)
        file(REMOVE ${local_path}/${name}.7z)
        set_property(GLOBAL PROPERTY zlib_AVAILABLE FALSE)
        return()
    endif()

    if (NOT EXISTS ${local_path}/include)
        file(ARCHIVE_EXTRACT INPUT ${local_path}/${name}.7z DESTINATION ${local_path})
    endif()

    _zlib_set_from_prefix(${local_path} ${os})
    set_property(GLOBAL PROPERTY zlib_AVAILABLE TRUE)
endfunction()

function(zlib_PopulateBuild local_path os arch build_type version)
    set(recipe_base "https://raw.githubusercontent.com/kryksyh/muse_deps_private/main")
    set(recipe_dir "${local_path}/recipe")
    file(MAKE_DIRECTORY "${recipe_dir}/patch")
    if (NOT EXISTS "${local_path}/build_dep_lib.cmake")
        file(DOWNLOAD ${recipe_base}/buildtools/build_dep_lib.cmake ${local_path}/build_dep_lib.cmake)
    endif()
    if (NOT EXISTS "${recipe_dir}/spec.cmake")
        file(DOWNLOAD ${recipe_base}/zlib/${version}/recipe/spec.cmake ${recipe_dir}/spec.cmake)
    endif()
    include("${recipe_dir}/spec.cmake")
    string(TOUPPER ${os} _os)
    foreach(pf ${DEP_PATCHES} ${DEP_PATCHES_${_os}})
        if (NOT EXISTS "${recipe_dir}/${pf}")
            file(DOWNLOAD ${recipe_base}/zlib/${version}/recipe/${pf} ${recipe_dir}/${pf})
        endif()
    endforeach()

    message(STATUS "[zlib] building from source -> ${local_path}")
    include("${local_path}/build_dep_lib.cmake")
    build_dep(NAME zlib RECIPE_DIR "${recipe_dir}" OS ${os} ARCH ${arch}
              BUILDTYPE ${build_type} WORK "${local_path}/work" INSTALL_DIR "${local_path}")

    _zlib_set_from_prefix(${local_path} ${os})
endfunction()

function(zlib_PopulateSystem)
    find_path(zlib_INCLUDE_DIR NAMES zlib.h)
    find_library(zlib_LIBRARY NAMES z)
    if (NOT zlib_INCLUDE_DIR OR NOT zlib_LIBRARY)
        message(FATAL_ERROR "[zlib] system zlib not found (USE_SYSTEM enabled)")
    endif()
    if(NOT TARGET zlib::zlib)
       add_library(zlib::zlib INTERFACE IMPORTED GLOBAL)
       target_include_directories(zlib::zlib INTERFACE ${zlib_INCLUDE_DIR})
       target_link_libraries(zlib::zlib INTERFACE ${zlib_LIBRARY})
    endif()
    set_property(GLOBAL PROPERTY zlib_INCLUDE_DIRS ${zlib_INCLUDE_DIR})
    set_property(GLOBAL PROPERTY zlib_LIBRARIES ${zlib_LIBRARY})
    set_property(GLOBAL PROPERTY zlib_INSTALL_LIBRARIES "")
endfunction()
